on:
  push:
    branches:
      - main
    paths:
      - '.github/*'
      - 'Makefile'
      - 'Dockerfile'
      - 'vendor/*'
      - 'go.mod'
      - 'go.sum'
      - '*.go'

jobs:

  build:
    name: Build, push, and deploy
    runs-on: ubuntu-latest
    steps:

    - name: Checkout master
      uses: actions/checkout@master

    - name: Pull latest cache image
      run: make pull-latest

    - name: Build container image
      run: make build
        
    - name: GHCR Login
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.CR_PAT }}
        
    - name: Push image to Github Container Registry
      run: make push

    - name: Install doctl
      uses: digitalocean/action-doctl@v2
      with:
        token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

    - name: Save DigitalOcean kubeconfig with short-lived credentials
      run: doctl kubernetes cluster kubeconfig save --expiry-seconds 600 dank-dev-04

    - name: Deploy to DigitalOcean Kubernetes
      run: make deploy

    - name: Verify deployment
      run: kubectl rollout status statefulset/privcy-node
